kristw/encodable

packages/encodable/src/types/Encoding.ts
Set the type for channel's output.
=> fix: channelencoder typing

packages/encodable/src/encoders/ChannelEncoder.ts, packages/encodable/src/encoders/Encoder.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat: add overloading for encode value

packages/encodable/package.json, packages/encodable/src/encoders/ChannelEncoder.ts, packages/encodable/src/fillers/completeAxisConfig.ts, packages/encodable/src/fillers/inferScaleType.ts, packages/encodable/src/parsers/format/createFormatterFromFieldTypeAndFormat.ts, packages/encodable/src/parsers/format/fallbackFormatter.ts, packages/encodable/src/parsers/scale/applyNice.ts, packages/encodable/src/parsers/scale/createScaleFromScaleConfig.ts, packages/encodable/src/parsers/scale/createScaleFromScaleType.ts, packages/encodable/src/types/ChannelDef.ts, packages/encodable/src/types/Data.ts, packages/encodable/src/types/Scale.ts, packages/encodable/src/utils/inferElementTypeFromUnionOfArrayTypes.ts, packages/encodable/test/encoders/Encoder.test.ts, packages/encodable/test/typeGuards/Base.test.ts
🏆 Enhancements
* remove `vega-expression` dependency
🏠 Internal
* remove unnecessary `eslint-disable`
* replace `any` with `unknown`
=> fix: remove `vega-expression` dependency

babel.config.js, package.json, packages/encodable/package.json
🏠 Internal
* Remove unnecessary transform
=> fix: remove babel transform runtime

babel.config.js, package.json
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> build: update config

packages/encodable/src/index.ts
🏆 Enhancements
* feat: export types and typeguards
* feat: export mergeEncoding
=> feat: export types typeguards and merge encoding utils

packages/encodable/src/index.ts
🏆 Enhancements
export `Channel`, `ChannelDef` and `Axis` types.
=> feat: export more types

packages/encodable/package.json, packages/encodable/src/encoders/ChannelEncoder.ts, packages/encodable/src/parsers/scale/applyRange.ts, packages/encodable/src/parsers/scale/createScaleFromScaleConfig.ts, packages/encodable/src/typeGuards/Scale.ts, packages/encodable/src/types/Scale.ts, packages/encodable/test/parsers/scale/createScaleFromScaleConfig.test.ts, packages/encodable/test/typeGuards/Scale.test.ts, yarn.lock
🏆 Enhancements
Support `scheme` being object in addition to string
```ts
type SchemeParams = { name, count, extent }
```
=> feat: support schemeparams similar to vega-lite

packages/encodable/src/parsers/scale/applyInterpolate.ts, packages/encodable/test/parsers/dateTimeToTimestamp.test.ts, packages/encodable/test/parsers/scale/applyInterpolate.test.ts, packages/encodable/test/parsers/scale/createScaleFromScaleConfig.test.ts
🏆  Enhancements
Enable color interpolator in continuous scales.
=> feat: support color interpolator

packages/encodable/package.json, packages/encodable/src/encoders/Encoder.ts, packages/encodable/src/parsers/createGetterFromChannelDef.ts, yarn.lock
🏠 Internal
Use only `get` from `lodash` and switch `flatMap` to js native.
=> feat: reduce lodash dependency

lerna.json, packages/singleton-store/README.md, packages/singleton-store/package.json, packages/singleton-store/src/Store.ts, packages/singleton-store/src/index.ts, packages/singleton-store/test/Store.test.ts, packages/singleton-store/test/index.test.ts
🏆 Enhancements
Create a new singleton-store package.
=> feat: create singleton-store

packages/singleton-store/src/getStore.ts, packages/singleton-store/src/index.ts, packages/singleton-store/test/index.test.ts
🏠 Internal
Add getter function for getting the store that warns if there are duplicates of `singleton-store`.
=> feat: add getStore

packages/singleton-store/README.md, packages/singleton-store/src/Store.ts, packages/singleton-store/src/getStore.ts, packages/singleton-store/test/Store.test.ts
Update function comments and README.
=> docs: add singleton-storage documentation

packages/encodable/package.json, packages/encodable/src/index.ts, packages/encodable/src/options/OptionsManager.ts, packages/encodable/src/parsers/format/createFormatter.ts, packages/encodable/src/parsers/format/createFormatterFromFieldTypeAndFormat.ts, packages/encodable/src/parsers/format/defaultNumberFormatResolver.ts, packages/encodable/src/parsers/format/defaultTimeFormatResolver.ts, packages/encodable/src/types/Options.ts, packages/encodable/test/options/OptionsManager.test.ts, packages/encodable/test/parsers/format/createFormatter.test.ts, yarn.lock
🏆  Enhancements
Can override and use external formatters.
=> feat: can customize format resolvers

packages/encodable/src/options/OptionsManager.ts, packages/encodable/src/parsers/format/createFormatter.ts, packages/encodable/src/parsers/format/defaultTimeFormatResolver.ts, packages/encodable/src/parsers/scale/applyRange.ts, packages/encodable/src/parsers/scale/defaultColorSchemeResolver.ts, packages/encodable/src/types/Options.ts, packages/encodable/test/options/OptionsManager.test.ts, packages/encodable/test/parsers/format/createFormatter.test.ts, packages/encodable/test/parsers/scale/applyRange.test.ts, packages/encodable/test/parsers/scale/defaultColorSchemeResolver.test.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat: add color scheme resolver

packages/encodable/src/parsers/scale/applyRange.ts, packages/encodable/src/parsers/scale/createScaleFromScaleConfig.ts, packages/encodable/src/parsers/scale/isPropertySupportedByScaleType.ts, packages/encodable/src/typeGuards/ScaleConfig.ts, packages/encodable/src/types/Scale.ts, packages/encodable/src/types/ScaleConfig.ts, packages/encodable/src/types/scale/BaseScaleConfig.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> fix: scale typings

packages/encodable/src/types/scale/ScaleConfig.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> fix: remove incompatible fields

package.json, packages/encodable-registry/package.json, packages/encodable/package.json, packages/generator-encodable/.gitattributes, packages/generator-encodable/README.md, packages/generator-encodable/generators/app/index.js, packages/generator-encodable/generators/package/index.js, packages/generator-encodable/generators/package/templates/README.md, packages/generator-encodable/generators/package/templates/_package.json, packages/generator-encodable/generators/package/templates/src/index.txt, packages/generator-encodable/generators/package/templates/test/index.txt, packages/generator-encodable/package.json, packages/generator-encodable/test/app.test.js, packages/generator-encodable/test/package.test.js, yarn.lock
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat(generator-encodable): add new generator package

packages/encodable-registry/src/index.ts, packages/encodable-registry/src/models/Registry.ts, packages/encodable-registry/src/types/index.ts, packages/encodable-registry/src/utils/makeSingleton.ts, packages/encodable-registry/test/models/Registry.test.ts, packages/encodable-registry/test/utils/makeSingleton.test.ts
🏆  Enhancements
* add `makeSingleton` utility function
* export config type and rename `registryId` to `globalId`
=> feat(registry): add makeSingleton

packages/encodable-format/src/time/factories/createMultiTimeFormatter.ts, packages/encodable-format/src/time/formatters/smartDate.ts, packages/encodable-format/src/time/formatters/smartDateVerbose.ts, packages/encodable-format/src/time/index.ts, packages/encodable-format/src/timeRange/index.ts, packages/encodable-format/test/time/factories/createMultiTimeFormatter.test.ts
* Rename `createMultiFormatter` to `createMultiTimeFormatter`
🏆 Enhancements
* export `TimeRangeFormatterRegistry`
=> feat: export TimeRangeFormatterRegistry class

package.json, packages/encodable-registry/src/models/Registry.ts, packages/encodable-registry/src/models/createRegistryStore.ts, packages/encodable-registry/src/types/index.ts, packages/encodable-registry/test/models/Registry.test.ts, yarn.lock
🏆 Enhancements
* Add `version` field to `config`
=> feat(registry): store schema version

packages/encodable-color/README.md, packages/encodable-color/package.json, packages/encodable-color/src/ColorSchemeRegistry.ts, packages/encodable-color/src/index.ts, packages/encodable-color/src/models/ExtensibleFunction.ts, packages/encodable-color/src/scale/ColorNamespace.ts, packages/encodable-color/src/scale/ColorNamespaceRegistry.ts, packages/encodable-color/src/scale/ScaleCategoricalColor.ts, packages/encodable-color/src/scale/index.ts, packages/encodable-color/src/scale/types.ts, packages/encodable-color/src/scheme/ChildRegistry.ts, packages/encodable-color/src/scheme/ColorSchemeRegistry.ts, packages/encodable-color/src/scheme/createWrapper.ts, packages/encodable-color/src/scheme/index.ts, packages/encodable-color/src/types.ts, packages/encodable-color/src/utils/stringifyAndTrim.ts, packages/encodable-color/test/index.test.ts, packages/encodable-color/test/models/ExtensibleFunction.test.ts, packages/encodable-color/test/scale/ColorNamespace.test.ts, packages/encodable-color/test/scale/ColorNamespaceRegistry.test.ts, packages/encodable-color/test/scale/ScaleCategoricalColor.test.ts, packages/encodable-color/test/scale/index.test.ts, packages/encodable-color/test/scheme/ColorSchemeRegistry.test.ts, packages/encodable-color/test/scheme/index.test.ts, yarn.lock
🏆 Enhancements
Add color scheme and namespace management
=> feat(color): add color scheme and namespaces

packages/encodable-registry/src/models/Registry.ts, packages/encodable-registry/test/models/Registry.test.ts
🏆 Enhancements
Add `registry.size()` and `registry.isEmpty()`.
=> feat(registry): add size and isEmpty function

packages/encodable-color/src/scheme/ChildRegistry.ts
🐛 Bug Fix
Fix issue that made looking up scheme from specific category with default key did not work.
=> fix(color): use child defaultKey

packages/encodable/src/index.ts, packages/encodable/src/types/Options.ts
🏆 Enhancements
re-export apis from color and formatters subpackages
=> feat(encodable): re-export apis from color and formatters

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/release.yml, DEMO.md, README.md, docs/createScaleFromScaleConfig.md, package.json, packages/encodable-color/CHANGELOG.md, packages/encodable-color/README.md, packages/encodable-color/package.json, packages/encodable-format/CHANGELOG.md, packages/encodable-format/README.md, packages/encodable-format/package.json, packages/encodable-registry/CHANGELOG.md, packages/encodable-registry/README.md, packages/encodable-registry/package.json, packages/encodable/CHANGELOG.md, packages/encodable/README.md, packages/encodable/package.json, packages/generator-encodable/CHANGELOG.md, packages/generator-encodable/README.md, packages/generator-encodable/generators/package/templates/README.md, packages/generator-encodable/generators/package/templates/_package.json, packages/generator-encodable/package.json
=> chore: update metadata

packages/docs/src/encodable/createScaleFromScaleConfig.md, packages/encodable-format/test/time/factories/createD3TimeFormatter.test.ts, packages/encodable/src/encoders/ChannelEncoder.ts, packages/encodable/src/index.ts, packages/encodable/src/parsers/scale/createScale.ts, packages/encodable/test/fillers/completeAxisConfig.test.ts, packages/encodable/test/parsers/scale/createScale.test.ts, packages/encodable/test/typeGuards/Base.test.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> refactor: rename createScale

packages/docs/doczrc.js, packages/docs/gatsby-config.js, packages/docs/package.json, packages/docs/src/gallery/index.mdx, packages/docs/src/gatsby-theme-docz/components/Header/styles.js, packages/docs/src/gatsby-theme-docz/theme/index.js, packages/docs/src/index.mdx, yarn.lock
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> docs: update style

packages/docs/gatsby-config.js, packages/docs/package.json, packages/docs/src/index.mdx, yarn.lock
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> docs: add google analytics

packages/docs/src/gallery/CoffeeChart.mdx
=> docs: simplify coffee chart spec

packages/docs/doczrc.js, packages/docs/src/about.mdx
=> docs: add link to paper

packages/encodable/src/encoders/ChannelEncoder.ts, packages/encodable/test/encoders/ChannelEncoder.test.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> fix: fallback when encoded value is undefined

package.json, packages/encodable-dimension/README.md, packages/encodable-dimension/package.json, packages/encodable-dimension/src/computeMaxFontSize.ts, packages/encodable-dimension/src/getMultipleTextDimensions.ts, packages/encodable-dimension/src/getTextDimension.ts, packages/encodable-dimension/src/index.ts, packages/encodable-dimension/src/mergeMargin.ts, packages/encodable-dimension/src/parseLength.ts, packages/encodable-dimension/src/svg/LazyFactory.ts, packages/encodable-dimension/src/svg/constants.ts, packages/encodable-dimension/src/svg/createHiddenSvgNode.ts, packages/encodable-dimension/src/svg/createTextNode.ts, packages/encodable-dimension/src/svg/factories.ts, packages/encodable-dimension/src/svg/getBBoxCeil.ts, packages/encodable-dimension/src/svg/updateTextNode.ts, packages/encodable-dimension/src/types.ts, packages/encodable-dimension/test/computeMaxFontSize.test.ts, packages/encodable-dimension/test/getBBoxDummyFill.ts, packages/encodable-dimension/test/getMultipleTextDimensions.test.ts, packages/encodable-dimension/test/getTextDimension.test.ts, packages/encodable-dimension/test/mergeMargin.test.ts, packages/encodable-dimension/test/parseLength.test.ts, packages/encodable-dimension/test/svg/LazyFactory.test.ts, packages/encodable-dimension/test/svg/getBBoxCeil.test.ts, packages/encodable-dimension/test/svg/updateTextNode.test.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat: add dimension utilities

packages/docs/doczrc.js, packages/docs/src/encodable-color/index.md, packages/docs/src/encodable-dimension/index.md, packages/docs/src/encodable-format/index.md, packages/docs/src/encodable-registry/index.md, packages/docs/src/encodable/ChannelDef.md, packages/docs/src/encodable/ChannelEncoder.md, packages/docs/src/encodable/ChannelType.md, packages/docs/src/encodable/Encoder.md, packages/docs/src/encodable/createScale.md, packages/docs/src/index.mdx, packages/docs/src/motivation.md
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> docs: add dimension documentation

packages/encodable/package.json, packages/encodable/src/index.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat: export dimension functions as part of main package

packages/docs/src/components/ScatterPlot/index.ts, packages/docs/src/components/SketchBarChart/index.tsx, packages/docs/src/gallery/Gallery.tsx, packages/encodable-dimension/src/mergeMargin.ts, packages/encodable/src/utils/inferElementTypeFromUnionOfArrayTypes.ts, packages/encodable/test/encoders/Encoder.test.ts
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> fix: minor typing

packages/docs/package.json, packages/docs/src/components/AreaChart/index.tsx, packages/docs/src/components/BalloonPlot/index.tsx, packages/docs/src/components/CoffeeChart/index.tsx, packages/docs/src/components/DonutChart/Encoder.ts, packages/docs/src/components/DonutChart/index.tsx, packages/docs/src/components/ScatterPlot/index.ts, packages/docs/src/components/SketchBarChart/index.tsx, packages/docs/src/gallery/BalloonPlot.mdx, packages/docs/src/gallery/DonutChart.mdx, packages/docs/src/gallery/Gallery.tsx, packages/docs/src/gallery/ScatterPlot.mdx, packages/docs/src/gallery/WordCloud.mdx, yarn.lock
=> docs: add donut chart

packages/encodable-dimension/src/types.ts
🏆 Enhancements
Add convenient types
=> feat(dimension): add WithPadding and WithMargin

packages/encodable/src/types/scale/ScaleConfig.ts
=> fix: allow scale to be disabled

packages/docs/package.json, packages/docs/src/components/AreaChart/index.tsx, packages/encodable-color/package.json, packages/encodable-color/src/scheme/wrappers/ContinuousSchemeWrapper.ts, packages/encodable/package.json, packages/encodable/test/typeGuards/Scale.test.ts, yarn.lock
🏆 Enhancements
🐛 Bug Fix
🏠 Internal
=> feat: bump d3-scale-type
